### ISSUE TITLE
测试结果有问题

### ISSUE THREAD

**Issue by lxtGH** [gasvn/Res2Net-Pose-Estimation#1]
这个用了Ground Truth BBOX，结果虚高，希望纠正。

**Comment by gasvn** [comment]
We follow the simple baseline to use their evaluation method. We intend to prove the effectiveness of Res2Net. You are welcomed to provide other avilable evaluation methods.

**Comment by lxtGH** [comment]
See this issue.https://github.com/microsoft/human-pose-estimation.pytorch/issues/55
You should set the USE_GT_BBOX  opinion False in the config file https://github.com/gasvn/Res2Net-Pose-Estimation/blob/master/experiments/coco/res2net/res2net101_4s_26w_256x192_d256x3_adam_lr1e-3.yaml

**Comment by gasvn** [comment]
Thanks, it seems the author's config is not the config used to reproduce the reported results.
Still, according to the link you provided, the Res2Net based method outperform the baseline when using gt box.
 pose_resnet_50 | 0.724 | 0.915 | 0.804 | 0.697 | 0.765
 pose_res2net_50 | 0.737 | 0.925 | 0.814 | 0.708 | 0.782
we will update the performance based on both gt box and the person detector's results ASAP.

**Comment by gasvn** [comment]
We have updated the results based on both gt box and the person detector's results. Thanks again for your notification.
